#ufw install

- name: Apt cache update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Package installation
  apt:
    name:
      - ufw
    state: present

#ufw config
- name: Set logging
  community.general.ufw:
    logging: 'on'

- name: Allow http traffic
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow https traffic
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Allow ssh traffic
  community.general.ufw:
    rule: allow
    port: '2233'
    proto: tcp

- name: Enabling ufw
  community.general.ufw:
    state: enabled
    policy: deny