#ufw install

- name: Apt cache update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Package installation
  apt:
    name:
      - ufw
    state: present

#ufw config
- name: Set logging
  community.general.ufw:
    logging: 'on'

- name: Allow http traffic
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow https traffic
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Allow ssh traffic
  community.general.ufw:
    rule: allow
    port: '2233'
    proto: tcp

- name: Allow Jenkins traffic
  community.general.ufw:
    rule: allow
    port: '8080'
    proto: tcp

- name: Allow traffic for K3s apiserver
  community.general.ufw:
    rule: allow
    port: '6443'
    proto: tcp

- name: Allow K3s Pod network
  community.general.ufw:
    rule: allow
    from_ip: '10.42.0.0/16'

- name: Allow K3s Service network
  community.general.ufw:
    rule: allow
    from_ip: '10.43.0.0/16'

- name: Allow K3s NodePort range
  community.general.ufw:
    rule: allow
    port: '30000:32767'
    proto: tcp

- name: Enabling ufw
  community.general.ufw:
    state: enabled
    policy: deny

- name: Ensure ufw service is enabled and started
  service:
    name: ufw
    state: started
    enabled: yes