- name: App server configuration
  hosts: all
  become: yes
  vars:
    ansible_become_flags: '-i'
  roles:
    - common
    - user-configuration
    - ssh-settings
    - jdk-setup
    - git-install-and-config
    - ufw-install-and-config
    - fail2ban-install-and-config
    - k3s-install
    - helm-and-ingress-install
    - scripting-tasks